"""add_email_templates_table

Revision ID: b8458d78f6ca
Revises: b3862f306a99
Create Date: 2026-01-28 14:01:15.443539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8458d78f6ca'
down_revision: Union[str, None] = 'b3862f306a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('FOLLOW_UP', 'INTRODUCTION', 'QUOTE', 'THANK_YOU', 'APPOINTMENT', 'CUSTOM', name='templatecategory'), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('available_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('dealership_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dealership_id'], ['dealerships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_templates_created_by'), 'email_templates', ['created_by'], unique=False)
    op.create_index(op.f('ix_email_templates_dealership_id'), 'email_templates', ['dealership_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_templates_dealership_id'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_created_by'), table_name='email_templates')
    op.drop_table('email_templates')
    # ### end Alembic commands ###
